#!/bin/bash

# Create the LED brightness sequences.

OutputFile=led-sequences.inc

[ -f "$OutputFile" ] && {
	cat 1>&2 <<EOF
$0: cowardly refusing to run because $OutputFile exists
EOF
	exit 1
}

usage () {
	cat 1>&2 <<EOF
Usage: $0 maxpwm
  creates $OutputFile
  will not run if $OutputFile exists
EOF
	exit 1
}

[ $# -ne 1 ] && usage

PWM="$1"

PWMLIST=( )

PWMtemp="$PWM"
while [ x0 != x"$PWMtemp" ] ; do
	PWMLIST=( "$PWMtemp" "${PWMLIST[@]}" )
	PWMtemp=$(( PWMtemp * 5 / 6 ))
done
NPWMS=${#PWMLIST[*]}

TotalCount=0

make_sequence () {
	local Name
	local Repeats
	local Count
	Name=$1
	Repeats=$2
	Count=0
	printf 'static const uint8_t PROGMEM %s[] = {\n' "$Name"
	for i in `seq 0 $((NPWMS-1))` ; do
		printf '\t'
		printf '%d,' ${PWMLIST[$i]}
		for j in `seq 2 $(($Repeats + ($RANDOM % 3) ))` ; do
			printf ' %d,' ${PWMLIST[$i]}
			Count=$((Count+1))
		done
		printf '\n'
	done
	for i in `seq $((NPWMS-1)) -1 0` ; do
		printf '\t'
		printf '%d,' ${PWMLIST[$i]}
		for j in `seq 2 $Repeats` ; do
			printf ' %d,' ${PWMLIST[$i]}
			Count=$((Count+1))
		done
		printf '\n'
	done
	printf '\t0 }; /* %d */\n\n' $Count
	TotalCount=$((TotalCount + Count))
}

exec >"$OutputFile"
printf '/* Generated by "%s %d" */\n' "$0" "$PWM"
printf '/*    at %s */\n' "$(date -Is)"
printf '/* N=%d: %s */\n\n' $NPWMS "${PWMLIST[*]}"
make_sequence pwm0 1
make_sequence pwm1 2
make_sequence pwm2 3
make_sequence pwm3 5
make_sequence pwm4 8
printf '/* Total: %d */\n' $TotalCount
